// <auto-generated/>
using System.Reflection;

[assembly: AssemblyCompanyAttribute("Yaaf.DependencyInjection.Ninject")]
[assembly: AssemblyProductAttribute("Yaaf.DependencyInjection.Ninject")]
[assembly: AssemblyCopyrightAttribute("Yaaf.DependencyInjection Copyright © Matthias Dittrich 2015")]
[assembly: AssemblyVersionAttribute("1.1.1")]
[assembly: AssemblyFileVersionAttribute("1.1.1")]
[assembly: AssemblyInformationalVersionAttribute("1.1.1")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.1.1";
    }
}
