// <auto-generated/>
using System.Reflection;

[assembly: AssemblyCompanyAttribute("Yaaf.DependencyInjection.SimpleInjector")]
[assembly: AssemblyProductAttribute("Yaaf.DependencyInjection.SimpleInjector")]
[assembly: AssemblyCopyrightAttribute("Yaaf.DependencyInjection Copyright © Matthias Dittrich 2015")]
[assembly: AssemblyVersionAttribute("1.1.0")]
[assembly: AssemblyFileVersionAttribute("1.1.0")]
[assembly: AssemblyInformationalVersionAttribute("1.1.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.1.0";
    }
}
